//! Compile the preamble's air-interface constants into the crate.
//!
//! The Schmidl–Cox and chip sequences are exported from the reference model by
//! `tools/make_phy_tables.py`. They are fixed constants that two stations must agree on
//! exactly, so they are data, not something to be regenerated by reimplementing the model's
//! random number generator. One [`Tables`] per waveform: the wide 2 300 Hz one and the
//! narrow 500 Hz one, which have different carrier maps, different chip sets and different
//! acquisition thresholds but the same shape.

use std::{env, fmt::Write as _, fs, path::PathBuf};

/// Hex-packed sign bits (1 meaning −1) back into `+1.0 / -1.0`.
fn unpack_signs(hex: &str, len: usize) -> Vec<f64> {
    let bytes: Vec<u8> = (0..hex.len() / 2)
        .map(|i| u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).expect("bad hex"))
        .collect();
    (0..len)
        .map(|i| {
            if (bytes[i / 8] >> (7 - i % 8)) & 1 == 1 {
                -1.0
            } else {
                1.0
            }
        })
        .collect()
}

fn literal(values: &[f64]) -> String {
    let mut out = String::new();
    for value in values {
        let _ = write!(out, "{value:?}, ");
    }
    out
}

/// One waveform's block of the JSON as Rust statics under `prefix`, plus its `Tables`.
#[allow(clippy::too_many_lines)]
fn waveform(out: &mut String, prefix: &str, doc: &serde_json::Value, n_rv: usize) {
    let sc_len = doc["sc_length"].as_u64().expect("sc_length") as usize;
    let chip_len = doc["chip_length"].as_u64().expect("chip_length") as usize;
    let n_modes = doc["n_modes"].as_u64().expect("n_modes") as usize;
    let bandwidth = doc["bandwidth_hz"].as_u64().expect("bandwidth_hz") as usize;

    let even: Vec<String> = doc["even_carriers"]
        .as_array()
        .expect("even_carriers")
        .iter()
        .map(|v| v.as_u64().expect("carrier").to_string())
        .collect();
    let _ = writeln!(
        out,
        "static {prefix}_EVEN_CARRIERS: [usize; {}] = [{}];",
        even.len(),
        even.join(", ")
    );
    for (name, key) in [("SC_DATA", "DATA"), ("SC_CONTROL", "CONTROL")] {
        let hex = doc["schmidl_cox"][key].as_str().expect("sc sequence");
        let _ = writeln!(
            out,
            "static {prefix}_{name}: [f64; {sc_len}] = [{}];",
            literal(&unpack_signs(hex, sc_len))
        );
    }
    // chips flat, row-major: sequence `i` is `[i * chip_length .. (i + 1) * chip_length]`
    let _ = writeln!(
        out,
        "static {prefix}_MODE_CHIPS: [f64; {}] = [",
        n_rv * n_modes * chip_len
    );
    for rv in 0..n_rv {
        for mode in 0..n_modes {
            let hex = doc["mode_chips"][format!("{rv}_{mode}")]
                .as_str()
                .expect("chip sequence");
            let _ = writeln!(out, "    {}", literal(&unpack_signs(hex, chip_len)));
        }
    }
    out.push_str("];\n");
    // The floor family (ADR-0009): its preamble sequences occupy every carrier and its chips
    // run over every full pilot symbol of the floor data layout; empty on an air without one.
    let floor_sc_len = doc["floor_sc_length"].as_u64().unwrap_or(0) as usize;
    let floor_chip_len = doc["floor_chip_length"].as_u64().unwrap_or(0) as usize;
    let floor_modes = doc["floor_modes"].as_u64().unwrap_or(0) as usize;
    let control_mode_index = doc["control_mode_index"].as_u64().unwrap_or(0) as usize;
    let floor_threshold = doc["floor_acquisition_threshold"].as_f64().unwrap_or(1.0);
    for (name, key) in [("FLOOR_SC_DATA", "DATA"), ("FLOOR_SC_CONTROL", "CONTROL")] {
        let signs = doc["floor_schmidl_cox"][key]
            .as_str()
            .map_or_else(Vec::new, |hex| unpack_signs(hex, floor_sc_len));
        let _ = writeln!(
            out,
            "static {prefix}_{name}: [f64; {}] = [{}];",
            signs.len(),
            literal(&signs)
        );
    }
    let floor_chip_count = if floor_chip_len == 0 {
        0
    } else {
        n_rv * n_modes
    };
    let _ = writeln!(
        out,
        "static {prefix}_FLOOR_MODE_CHIPS: [f64; {}] = [",
        floor_chip_count * floor_chip_len
    );
    if floor_chip_len > 0 {
        for rv in 0..n_rv {
            for mode in 0..n_modes {
                let hex = doc["floor_mode_chips"][format!("{rv}_{mode}")]
                    .as_str()
                    .expect("floor chip sequence");
                let _ = writeln!(out, "    {}", literal(&unpack_signs(hex, floor_chip_len)));
            }
        }
    }
    out.push_str("];\n");
    let pilots = doc["pilot_sequence"].as_array().expect("pilot_sequence");
    let _ = writeln!(
        out,
        "static {prefix}_PILOT_SEQUENCE: [(f64, f64); {}] = [",
        pilots.len()
    );
    for point in pilots {
        let (re, im) = (
            point[0].as_f64().expect("re"),
            point[1].as_f64().expect("im"),
        );
        let _ = writeln!(out, "    ({re:?}, {im:?}),");
    }
    out.push_str("];\n");
    let _ = writeln!(
        out,
        "pub(crate) static {prefix}: Tables = Tables {{\n    bandwidth_hz: {bandwidth},\n    \
         sc_length: {sc_len},\n    chip_length: {chip_len},\n    n_modes: {n_modes},\n    \
         chip_correlation_bound: {:?},\n    acquisition_threshold: {:?},\n    \
         even_carriers: &{prefix}_EVEN_CARRIERS,\n    sc_data: &{prefix}_SC_DATA,\n    \
         sc_control: &{prefix}_SC_CONTROL,\n    mode_chips: &{prefix}_MODE_CHIPS,\n    \
         pilot_sequence: &{prefix}_PILOT_SEQUENCE,\n    \
         floor_sc_length: {floor_sc_len},\n    floor_chip_length: {floor_chip_len},\n    \
         floor_modes: {floor_modes},\n    control_mode_index: {control_mode_index},\n    \
         floor_acquisition_threshold: {floor_threshold:?},\n    \
         floor_sc_data: &{prefix}_FLOOR_SC_DATA,\n    \
         floor_sc_control: &{prefix}_FLOOR_SC_CONTROL,\n    \
         floor_mode_chips: &{prefix}_FLOOR_MODE_CHIPS,\n}};",
        doc["chip_correlation_bound"]
            .as_f64()
            .expect("chip_correlation_bound"),
        doc["acquisition_threshold"]
            .as_f64()
            .expect("acquisition_threshold"),
    );
}

fn main() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data/preamble_tables.json");
    println!("cargo:rerun-if-changed={}", path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let text = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read {} ({e}); run tools/make_phy_tables.py",
            path.display()
        )
    });
    let doc: serde_json::Value = serde_json::from_str(&text).expect("preamble table is not JSON");
    let n_rv = doc["n_rv"].as_u64().expect("n_rv") as usize;

    let mut out = String::new();
    out.push_str("// @generated by build.rs from data/preamble_tables.json - do not edit.\n\n");
    let _ = writeln!(out, "pub(crate) const N_RV: usize = {n_rv};");
    out.push_str(
        "/// One waveform's air-interface constants.\n\
         #[derive(Debug)]\n\
         pub(crate) struct Tables {\n    \
             pub bandwidth_hz: usize,\n    \
             pub sc_length: usize,\n    \
             pub chip_length: usize,\n    \
             pub n_modes: usize,\n    \
             pub chip_correlation_bound: f64,\n    \
             pub acquisition_threshold: f64,\n    \
             pub even_carriers: &'static [usize],\n    \
             pub sc_data: &'static [f64],\n    \
             pub sc_control: &'static [f64],\n    \
             /// Row-major: sequence `i` is `[i * chip_length .. (i + 1) * chip_length]`.\n    \
             pub mode_chips: &'static [f64],\n    \
             pub pilot_sequence: &'static [(f64, f64)],\n    \
             /// The floor family (ADR-0009); zero-length on an air without one.\n    \
             pub floor_sc_length: usize,\n    \
             pub floor_chip_length: usize,\n    \
             pub floor_modes: usize,\n    \
             pub control_mode_index: usize,\n    \
             pub floor_acquisition_threshold: f64,\n    \
             /// On every active carrier, not the even ones only.\n    \
             pub floor_sc_data: &'static [f64],\n    \
             pub floor_sc_control: &'static [f64],\n    \
             /// Row-major like `mode_chips`, `floor_chip_length` chips a sequence.\n    \
             pub floor_mode_chips: &'static [f64],\n\
         }\n\n",
    );
    let waveforms = doc["waveforms"].as_object().expect("waveforms");
    let mut names = Vec::new();
    for (name, block) in waveforms {
        waveform(&mut out, name, block, n_rv);
        names.push(name.clone());
    }
    let _ = writeln!(
        out,
        "/// The tables of the waveform with this nominal bandwidth, if it has any.\n\
         pub(crate) fn for_bandwidth(hz: usize) -> Option<&'static Tables> {{\n    \
             [{}].into_iter().find(|t| t.bandwidth_hz == hz)\n\
         }}",
        names
            .iter()
            .map(|n| format!("&{n}"))
            .collect::<Vec<_>>()
            .join(", ")
    );

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("preamble_tables.rs");
    fs::write(&dest, out).expect("cannot write generated preamble tables");
}
