//! Compile the preamble's air-interface constants into the crate.
//!
//! The Schmidl–Cox and chip sequences are exported from the reference model by
//! `tools/make_phy_tables.py`. They are fixed constants that two stations must agree on
//! exactly, so they are data, not something to be regenerated by reimplementing the model's
//! random number generator.

use std::{env, fmt::Write as _, fs, path::PathBuf};

/// Hex-packed sign bits (1 meaning −1) back into `+1.0 / -1.0`.
fn unpack_signs(hex: &str, len: usize) -> Vec<f64> {
    let bytes: Vec<u8> = (0..hex.len() / 2)
        .map(|i| u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).expect("bad hex"))
        .collect();
    (0..len)
        .map(|i| {
            if (bytes[i / 8] >> (7 - i % 8)) & 1 == 1 {
                -1.0
            } else {
                1.0
            }
        })
        .collect()
}

fn literal(values: &[f64]) -> String {
    let mut out = String::new();
    for value in values {
        let _ = write!(out, "{value:?}, ");
    }
    out
}

fn main() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data/preamble_tables.json");
    println!("cargo:rerun-if-changed={}", path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let text = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read {} ({e}); run tools/make_phy_tables.py",
            path.display()
        )
    });
    let doc: serde_json::Value = serde_json::from_str(&text).expect("preamble table is not JSON");

    let sc_len = doc["sc_length"].as_u64().expect("sc_length") as usize;
    let chip_len = doc["chip_length"].as_u64().expect("chip_length") as usize;
    let n_rv = doc["n_rv"].as_u64().expect("n_rv") as usize;
    let n_modes = doc["n_modes"].as_u64().expect("n_modes") as usize;

    let mut out = String::new();
    out.push_str("// @generated by build.rs from data/preamble_tables.json - do not edit.\n\n");
    let _ = writeln!(out, "pub(crate) const SC_LENGTH: usize = {sc_len};");
    let _ = writeln!(out, "pub(crate) const CHIP_LENGTH: usize = {chip_len};");
    let _ = writeln!(out, "pub(crate) const N_RV: usize = {n_rv};");
    let _ = writeln!(out, "pub(crate) const N_MODES: usize = {n_modes};");

    let even: Vec<usize> = doc["even_carriers"]
        .as_array()
        .expect("even_carriers")
        .iter()
        .map(|v| v.as_u64().expect("carrier") as usize)
        .collect();
    let _ = writeln!(
        out,
        "pub(crate) static EVEN_CARRIERS: [usize; {}] = [{}];",
        even.len(),
        even.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    );

    for (name, key) in [("SC_DATA", "DATA"), ("SC_CONTROL", "CONTROL")] {
        let hex = doc["schmidl_cox"][key].as_str().expect("sc sequence");
        let _ = writeln!(
            out,
            "pub(crate) static {name}: [f64; {sc_len}] = [{}];",
            literal(&unpack_signs(hex, sc_len))
        );
    }

    let _ = writeln!(
        out,
        "pub(crate) static MODE_CHIPS: [[f64; {chip_len}]; {}] = [",
        n_rv * n_modes
    );
    for rv in 0..n_rv {
        for mode in 0..n_modes {
            let hex = doc["mode_chips"][format!("{rv}_{mode}")]
                .as_str()
                .expect("chip sequence");
            let _ = writeln!(out, "    [{}],", literal(&unpack_signs(hex, chip_len)));
        }
    }
    out.push_str("];\n");

    let pilots = doc["pilot_sequence"].as_array().expect("pilot_sequence");
    let _ = writeln!(
        out,
        "pub(crate) static PILOT_SEQUENCE: [(f64, f64); {}] = [",
        pilots.len()
    );
    for point in pilots {
        let (re, im) = (
            point[0].as_f64().expect("re"),
            point[1].as_f64().expect("im"),
        );
        let _ = writeln!(out, "    ({re:?}, {im:?}),");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("preamble_tables.rs");
    fs::write(&dest, out).expect("cannot write generated preamble tables");
}
