"""The occupancy table the regulatory gate reads is what the transmitter occupies (ADR-0018).

`core/aetherd/data/occupancy.json` is generated by `tools/make_occupancy.py`; this measures
the model's transmitter again and holds the committed table to it, a spectrum bin either way
(a threshold crossing can land a bin apart on another platform's FFT). A waveform or filter
change that moves an edge further makes this fail until the table is generated again.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
TABLE = ROOT / "core" / "aetherd" / "data" / "occupancy.json"


def _tool():  # type: ignore[no-untyped-def]
    path = ROOT / "tools" / "make_occupancy.py"
    spec = importlib.util.spec_from_file_location("make_occupancy", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["make_occupancy"] = module
    spec.loader.exec_module(module)
    return module


@pytest.mark.slow
def test_the_committed_occupancy_is_what_the_transmitter_occupies() -> None:
    tool = _tool()
    committed = json.loads(TABLE.read_text(encoding="utf-8"))
    fresh = tool.build()
    tolerance = fresh["resolution_hz"] + 1e-6
    assert set(committed["airs"]) == set(fresh["airs"])
    for air, measured in fresh["airs"].items():
        kept = committed["airs"][air]
        assert len(kept["rungs"]) == len(measured["rungs"])
        pairs = list(zip(kept["rungs"], measured["rungs"], strict=True))
        pairs += [(kept["control"][k], measured["control"][k]) for k in ("ordinary", "floor")]
        for old, new in pairs:
            for reading in ("power", "spectral"):
                for a, b in zip(old[reading], new[reading], strict=True):
                    assert abs(a - b) <= tolerance, (air, old.get("name"), reading, a, b)


def test_every_emission_is_measured_wider_than_it_is_named() -> None:
    """What the regulatory decisions rest on, pinned where the table is read: the narrow
    air's OFDM rungs exceed 500 Hz under either reading of §97.3(a)(8), and the tone floor
    is under it as a ratio of powers but over it as a spectral level."""
    table = json.loads(TABLE.read_text(encoding="utf-8"))
    narrow = table["airs"]["500"]

    def width(edges: list[float]) -> float:
        return edges[1] - edges[0]

    for rung in narrow["rungs"]:
        if rung["family"] == "ofdm":
            assert width(rung["power"]) > 500 and width(rung["spectral"]) > 500
    floor = narrow["rungs"][0]
    assert width(floor["power"]) < 500 < width(floor["spectral"])
    for air in table["airs"].values():
        for rung in air["rungs"]:
            assert width(rung["spectral"]) >= width(rung["power"])
            assert width(rung["spectral"]) < 2800, "every rung within §97.307(f)(3)"
