"""Export the preamble's fixed sequences for the Rust core (roadmap P3-2).

    python tools/make_phy_tables.py [--out core/aether-phy/data/preamble_tables.json]

The Schmidl–Cox sequences and the (redundancy version, mode) chip sequences are *air-
interface constants*: two stations must use identical ones or they cannot talk. In the model
they happen to be produced by a seeded NumPy generator, which is a convenient way to pick
well-separated pseudo-random sequences — not something a second implementation should try to
reproduce by reimplementing PCG64. So they are exported here as data and compiled into the
core, exactly as the LDPC base graphs are, and the specification carries the seeds only as
provenance.

Sequences are ±1, stored as bits (1 meaning −1) packed MSB-first into hex.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "model"))

from aether_model.phy.ofdm import PILOT_ROOT, carrier_map, zadoff_chu
from aether_model.phy.preamble import (
    MODE_CHIP_SEED,
    N_MODES,
    N_RV,
    SC_SEEDS,
    FrameType,
    chip_index,
    mode_chip_sequences,
    preamble,
)
from aether_model.waveform import WIDE_2300 as P


def pack_signs(values: np.ndarray) -> str:
    """±1 values → bits (1 meaning −1), MSB-first, hex."""
    bits = (np.asarray(values).real < 0).astype(np.uint8)
    return np.packbits(bits).tobytes().hex()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default="core/aether-phy/data/preamble_tables.json")
    args = ap.parse_args()

    pre = preamble(P)
    cmap = carrier_map(P)
    even = np.asarray(pre.even)

    # The Schmidl-Cox symbols carry a PN sequence on the even carriers only; recover the raw
    # signs by dividing out the power-normalising scale the model applies.
    sc = {}
    for frame_type in FrameType:
        values = pre.sc_values(frame_type)[even]
        sc[frame_type.name] = pack_signs(values / np.abs(values).mean())

    chips = mode_chip_sequences(pre.n_chips)
    chip_table = {}
    for rv in range(N_RV):
        for mode in range(N_MODES):
            chip_table[f"{rv}_{mode}"] = pack_signs(chips[chip_index(mode, rv)])

    document = {
        "note": "Generated by tools/make_phy_tables.py. Air-interface constants: sequences "
        "are +-1, stored as bits (1 means -1) packed MSB-first into hex.",
        "seeds": {
            "schmidl_cox": {
                k.name if hasattr(k, "name") else str(k): v for k, v in SC_SEEDS.items()
            },
            "mode_chips": MODE_CHIP_SEED,
        },
        "n_carriers": int(cmap.n_carriers),
        "even_carriers": [int(c) for c in even],
        "sc_length": len(even),
        "schmidl_cox": sc,
        "n_rv": N_RV,
        "n_modes": N_MODES,
        "chip_length": int(pre.n_chips),
        "chips_per_symbol": int(pre.n_data),
        "mode_chips": chip_table,
        "pilot_root": PILOT_ROOT,
        "pilot_sequence": [
            [float(v.real), float(v.imag)] for v in zadoff_chu(cmap.n_carriers, PILOT_ROOT)
        ],
    }

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(document, indent=1) + "\n", encoding="utf-8", newline="\n")
    print(
        f"wrote {out} (SC {len(sc)} x {document['sc_length']}, "
        f"chips {len(chip_table)} x {document['chip_length']})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
