"""
aether_hf/dsp/channel.py

HF channel simulators for conformance testing.

Implements the Watterson model (tapped delay line with Rayleigh-fading
tap gains) for the ITU-R F.1487 reference channels, plus AWGN and
Middleton Class-A impulsive noise.

All simulators operate on complex baseband samples at 12 kHz.
"""

import numpy as np
from dataclasses import dataclass
from typing import Optional

from aether_hf.constants import BASEBAND_RATE


@dataclass
class ChannelProfile:
    """Definition of one ITU-R F.1487 channel model.

    Each tap has a delay (seconds) and Doppler spread (Hz).
    Tap gains are Rayleigh-distributed (complex Gaussian).
    """
    name:          str
    delays_s:      list[float]       # per-tap delay in seconds
    doppler_hz:    list[float]       # per-tap Doppler spread in Hz
    tap_powers_db: list[float]       # per-tap relative power in dB (0 = equal)


# ── ITU-R F.1487 Channel Profiles ─────────────────────────────────────

CHANNEL_GOOD = ChannelProfile(
    name="ITU Good",
    delays_s=[0.0, 0.5e-3],
    doppler_hz=[0.5, 0.5],
    tap_powers_db=[0.0, 0.0],
)

CHANNEL_MODERATE = ChannelProfile(
    name="ITU Moderate",
    delays_s=[0.0, 1.0e-3],
    doppler_hz=[1.0, 1.0],
    tap_powers_db=[0.0, 0.0],
)

CHANNEL_POOR = ChannelProfile(
    name="ITU Poor",
    delays_s=[0.0, 2.0e-3],
    doppler_hz=[2.0, 2.0],
    tap_powers_db=[0.0, 0.0],
)

CHANNEL_FLUTTER = ChannelProfile(
    name="ITU Flutter",
    delays_s=[0.0, 2.0e-3],
    doppler_hz=[10.0, 10.0],
    tap_powers_db=[0.0, 0.0],
)

CHANNEL_AWGN = ChannelProfile(
    name="AWGN",
    delays_s=[0.0],
    doppler_hz=[0.0],
    tap_powers_db=[0.0],
)

ALL_PROFILES = {
    "good":     CHANNEL_GOOD,
    "moderate": CHANNEL_MODERATE,
    "poor":     CHANNEL_POOR,
    "flutter":  CHANNEL_FLUTTER,
    "awgn":     CHANNEL_AWGN,
}


class WattersonChannel:
    """Watterson HF channel simulator.

    Models multipath propagation with Rayleigh-fading taps.  Each tap
    has an independent Doppler-spread fading process generated by
    filtering white Gaussian noise through a Gaussian-shaped Doppler
    spectrum.

    Usage:
        ch = WattersonChannel(CHANNEL_MODERATE, snr_db=10.0)
        rx = ch.process(tx_samples)
    """

    def __init__(self, profile: ChannelProfile, snr_db: float = 20.0,
                 sample_rate: float = BASEBAND_RATE, seed: int = 0):
        self.profile = profile
        self.snr_db = snr_db
        self._fs = sample_rate
        self._rng = np.random.RandomState(seed)

        self._n_taps = len(profile.delays_s)
        self._delay_samples = [int(d * sample_rate) for d in profile.delays_s]
        self._max_delay = max(self._delay_samples) if self._delay_samples else 0

        # Convert tap powers from dB to linear
        powers_lin = np.array([10 ** (p / 10) for p in profile.tap_powers_db])
        total = np.sum(powers_lin)
        self._tap_amplitudes = np.sqrt(powers_lin / total)  # normalize total power = 1

        # Fading process state (per tap)
        self._fading_state: list[complex] = [1.0 + 0j] * self._n_taps
        self._fading_phase: list[float] = [0.0] * self._n_taps

    def process(self, tx: np.ndarray) -> np.ndarray:
        """Pass transmit samples through the channel.

        Returns received samples with multipath fading and AWGN.
        """
        n = len(tx)

        # Pad input to accommodate delay spread
        padded = np.zeros(n + self._max_delay, dtype=np.complex128)
        padded[:n] = tx

        # Generate fading gains for each tap (block fading per sample)
        rx = np.zeros(n, dtype=np.complex128)

        for tap_idx in range(self._n_taps):
            delay = self._delay_samples[tap_idx]
            doppler = self.profile.doppler_hz[tap_idx]
            amp = self._tap_amplitudes[tap_idx]

            # Generate fading process
            fading = self._generate_fading(n, doppler)

            # Apply tap: delayed signal * fading gain * amplitude
            delayed = padded[delay:delay + n]
            rx += amp * fading * delayed

        # Add AWGN
        sig_power = np.mean(np.abs(rx) ** 2)
        if sig_power > 0:
            noise_power = sig_power / (10 ** (self.snr_db / 10))
        else:
            noise_power = 10 ** (-self.snr_db / 10)

        noise = np.sqrt(noise_power / 2) * (
            self._rng.randn(n) + 1j * self._rng.randn(n)
        )

        return rx + noise

    def _generate_fading(self, n: int, doppler_hz: float) -> np.ndarray:
        """Generate Rayleigh fading with given Doppler spread.

        Uses the Jakes model approximation: filter white Gaussian noise
        through a Gaussian-shaped Doppler spectrum.

        For doppler_hz == 0 (AWGN), returns constant gain of 1.0.
        """
        if doppler_hz <= 0:
            return np.ones(n, dtype=np.complex128)

        # Generate complex white noise
        wgn = (self._rng.randn(n) + 1j * self._rng.randn(n)) / np.sqrt(2)

        # Doppler filter in frequency domain
        # Gaussian Doppler spectrum: H(f) = exp(-f^2 / (2 * fd^2))
        freqs = np.fft.fftfreq(n, d=1.0 / self._fs)
        H_doppler = np.exp(-freqs ** 2 / (2 * doppler_hz ** 2))

        # Filter in frequency domain
        WGN_f = np.fft.fft(wgn)
        faded_f = WGN_f * H_doppler
        fading = np.fft.ifft(faded_f)

        # Normalize to unit average power
        power = np.mean(np.abs(fading) ** 2)
        if power > 0:
            fading /= np.sqrt(power)

        return fading


class ImpulsiveNoiseChannel:
    """Middleton Class-A impulsive noise channel.

    Adds impulsive noise on top of a base channel (Watterson or AWGN).
    Impulses occur with probability A and have power Gamma times the
    Gaussian noise floor.

    Parameters:
        A:     impulse probability (0.01 = 1% of samples, 0.1 = 10%)
        Gamma: impulse-to-Gaussian power ratio (0.01 = 20 dB above floor)
    """

    def __init__(self, base_channel: WattersonChannel,
                 A: float = 0.1, Gamma: float = 0.01, seed: int = 99):
        self._base = base_channel
        self._A = A
        self._Gamma = Gamma
        self._rng = np.random.RandomState(seed)

    def process(self, tx: np.ndarray) -> np.ndarray:
        """Pass through base channel, then add impulsive noise."""
        rx = self._base.process(tx)

        n = len(rx)
        sig_power = np.mean(np.abs(rx) ** 2)

        # Gaussian noise component is already in rx from base channel.
        # Add impulsive component: occurs with probability A, power = sig_power / Gamma
        impulse_mask = self._rng.rand(n) < self._A
        n_impulses = np.sum(impulse_mask)

        if n_impulses > 0:
            impulse_power = sig_power / max(self._Gamma, 1e-10)
            impulses = np.sqrt(impulse_power / 2) * (
                self._rng.randn(n_impulses) + 1j * self._rng.randn(n_impulses)
            )
            rx[impulse_mask] += impulses

        return rx


def make_channel(profile_name: str, snr_db: float,
                 impulsive: bool = False, seed: int = 0) -> object:
    """Factory function to create a channel simulator.

    Args:
        profile_name: "good", "moderate", "poor", "flutter", or "awgn"
        snr_db: Signal-to-noise ratio in dB
        impulsive: If True, add Middleton Class-A impulsive noise
        seed: Random seed for reproducibility

    Returns:
        Channel object with a .process(tx) method.
    """
    profile = ALL_PROFILES.get(profile_name.lower())
    if profile is None:
        raise ValueError(f"Unknown channel profile: {profile_name}. "
                         f"Available: {list(ALL_PROFILES.keys())}")

    base = WattersonChannel(profile, snr_db=snr_db, seed=seed)

    if impulsive:
        return ImpulsiveNoiseChannel(base, A=0.1, Gamma=0.01, seed=seed + 1000)

    return base
