//! Turn the extracted 3GPP base-graph tables into Rust constants at build time.
//!
//! The tables live in the Python reference model
//! (`model/aether_model/fec/data/nr_ldpc_base_graphs.json`, extracted from TS 38.212
//! Tables 5.3.2-2 and 5.3.2-3) and both implementations read that one file. Generating
//! Rust from it means the shipped crate carries no JSON parser and no runtime file
//! loading, while the model and the core provably share a single source of truth: if the
//! table ever changed, both would change together or the cross-validation tests would fail.

use std::{env, fmt::Write as _, fs, path::PathBuf};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("crate is two levels below the repository root")
        .to_path_buf();
    let json_path = root.join("model/aether_model/fec/data/nr_ldpc_base_graphs.json");
    println!("cargo:rerun-if-changed={}", json_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let text = fs::read_to_string(&json_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", json_path.display()));
    let root_value: serde_json::Value =
        serde_json::from_str(&text).expect("base-graph table is not valid JSON");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from nr_ldpc_base_graphs.json - do not edit.\n\n");

    for number in [1u8, 2] {
        let bg = &root_value[format!("bg{number}")];
        let rows = bg["rows"].as_u64().expect("rows") as usize;
        let cols = bg["cols"].as_u64().expect("cols") as usize;
        let entries = bg["entries"].as_array().expect("entries");

        let _ = writeln!(out, "pub(crate) const BG{number}_ROWS: usize = {rows};");
        let _ = writeln!(out, "pub(crate) const BG{number}_COLS: usize = {cols};");
        let _ = writeln!(
            out,
            "pub(crate) const BG{number}_ENTRIES: [(u16, u16, [u16; 8]); {}] = [",
            entries.len()
        );
        for entry in entries {
            let row = entry[0].as_u64().expect("entry row");
            let col = entry[1].as_u64().expect("entry column");
            let shifts = entry[2].as_array().expect("entry shifts");
            assert_eq!(shifts.len(), 8, "expected one shift per lifting set");
            let shifts: Vec<String> = shifts
                .iter()
                .map(|v| v.as_u64().expect("shift value").to_string())
                .collect();
            let _ = writeln!(out, "    ({row}, {col}, [{}]),", shifts.join(", "));
        }
        out.push_str("];\n\n");
    }

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("base_graphs.rs");
    fs::write(&dest, out).expect("cannot write generated tables");
}
